### ISSUE TITLE
Got error on running the pre-requisite check and caching step

### ISSUE THREAD

**Issue by balajikadambi** [gcharters/kabanero-dev-getting-started#11]
When I ran this command curl -sL https://github.com/gcharters/kabanero-dev-getting-started/releases/download/0.0.1/workshop-setup.sh | bash, I got the below error. 

Running hooks in /etc/ca-certificates/update.d...

Picked up JAVA_TOOL_OPTIONS: -XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle
done.
done.
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM dev.appsody:java-microprofile:[0.2, 0.3) for dev.appsody.starter.java-microprofile:starter-app:1.0-SNAPSHOT: No versions matched the requested parent version range '[0.2, 0.3)' and 'parent.relativePath' points at no local POM @ line 8, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project dev.appsody.starter.java-microprofile:starter-app:1.0-SNAPSHOT (/project/user-app/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM dev.appsody:java-microprofile:[0.2, 0.3) for dev.appsody.starter.java-microprofile:starter-app:1.0-SNAPSHOT: No versions matched the requested parent version range '[0.2, 0.3)' and 'parent.relativePath' points at no local POM @ line 8, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
The command '/bin/sh -c apt-get update &&     apt-get install -y maven unzip &&     sed -i "s|19.0.0.8|19.0.0.7|g" /project/pom.xml &&     mvn -q -B -f /project/user-app/pom.xml checkstyle:checkstyle install dependency:go-offline &&     mvn -q -B -f /project/pom-dev.xml checkstyle:checkstyle install dependency:go-offline &&     sed -i "s|19.0.0.7|19.0.0.8|g" /project/pom.xml &&     mvn -q -B -f /project/user-app/pom.xml dependency:go-offline &&     rm -rf /project' returned a non-zero code: 1

**Comment by nastacio** [comment]
Closed by https://github.com/gcharters/kabanero-dev-getting-started/commit/80045695aeeffc1f9326b2c74494e1e9f3f65a4f
